# GLOBAL CONFIGURATION
spring:
  application.name: agrinibank-service
  datasource:
    url: jdbc:mysql://172.16.8.26:3306/trs-connector
    username: finshot
    password: finshot
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
server:
  servlet.context-path: /
  port: 8685
  max-http-header-size: 10000000
  tomcat:
    basedir: D:/Tmp
